-- CreateTable
CREATE TABLE `Historique_phase1` (
    `Id` INTEGER NOT NULL AUTO_INCREMENT,
    `Date` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `Poste` ENUM('MATIN', 'APRES_MIDI', 'NUIT') NOT NULL,
    `Of` VARCHAR(191) NULL,
    `QP` INTEGER NOT NULL DEFAULT 0,
    `TQ` DOUBLE NOT NULL DEFAULT 0,
    `TP` DOUBLE NOT NULL DEFAULT 0,
    `TD` DOUBLE NOT NULL DEFAULT 0,
    `TR` DOUBLE NOT NULL DEFAULT 0,
    `TDech` DOUBLE NOT NULL DEFAULT 0,
    `TQ_AVG` DOUBLE NOT NULL DEFAULT 0,
    `TP_AVG` DOUBLE NOT NULL DEFAULT 0,
    `TD_AVG` DOUBLE NOT NULL DEFAULT 0,
    `TR_AVG` DOUBLE NOT NULL DEFAULT 0,
    `TDech_AVG` DOUBLE NOT NULL DEFAULT 0,
    `TQ_D` INTEGER NOT NULL DEFAULT 1,
    `TP_D` INTEGER NOT NULL DEFAULT 1,
    `TD_D` INTEGER NOT NULL DEFAULT 1,
    `TR_D` INTEGER NOT NULL DEFAULT 1,
    `TDech_D` INTEGER NOT NULL DEFAULT 1,
    `Cadence` DOUBLE NOT NULL,

    PRIMARY KEY (`Id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Historique_phase2` (
    `Id` INTEGER NOT NULL AUTO_INCREMENT,
    `Date` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `Poste` ENUM('MATIN', 'APRES_MIDI', 'NUIT') NOT NULL,
    `Of` VARCHAR(191) NULL,
    `QP` INTEGER NOT NULL DEFAULT 0,
    `TQ` DOUBLE NOT NULL DEFAULT 0,
    `TP` DOUBLE NOT NULL DEFAULT 0,
    `TD` DOUBLE NOT NULL DEFAULT 0,
    `TR` DOUBLE NOT NULL DEFAULT 0,
    `TDech` DOUBLE NOT NULL DEFAULT 0,
    `TQ_AVG` DOUBLE NOT NULL DEFAULT 0,
    `TP_AVG` DOUBLE NOT NULL DEFAULT 0,
    `TD_AVG` DOUBLE NOT NULL DEFAULT 0,
    `TR_AVG` DOUBLE NOT NULL DEFAULT 0,
    `TDech_AVG` DOUBLE NOT NULL DEFAULT 0,
    `TQ_D` INTEGER NOT NULL DEFAULT 1,
    `TP_D` INTEGER NOT NULL DEFAULT 1,
    `TD_D` INTEGER NOT NULL DEFAULT 1,
    `TR_D` INTEGER NOT NULL DEFAULT 1,
    `TDech_D` INTEGER NOT NULL DEFAULT 1,
    `Cadence` DOUBLE NOT NULL,

    PRIMARY KEY (`Id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Historique_phase3` (
    `Id` INTEGER NOT NULL AUTO_INCREMENT,
    `Date` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `Poste` ENUM('MATIN', 'APRES_MIDI', 'NUIT') NOT NULL,
    `Of` VARCHAR(191) NULL,
    `QP` INTEGER NOT NULL DEFAULT 0,
    `TQ` DOUBLE NOT NULL DEFAULT 0,
    `TP` DOUBLE NOT NULL DEFAULT 0,
    `TD` DOUBLE NOT NULL DEFAULT 0,
    `TR` DOUBLE NOT NULL DEFAULT 0,
    `TDech` DOUBLE NOT NULL DEFAULT 0,
    `TQ_AVG` DOUBLE NOT NULL DEFAULT 0,
    `TP_AVG` DOUBLE NOT NULL DEFAULT 0,
    `TD_AVG` DOUBLE NOT NULL DEFAULT 0,
    `TR_AVG` DOUBLE NOT NULL DEFAULT 0,
    `TDech_AVG` DOUBLE NOT NULL DEFAULT 0,
    `TQ_D` INTEGER NOT NULL DEFAULT 1,
    `TP_D` INTEGER NOT NULL DEFAULT 1,
    `TD_D` INTEGER NOT NULL DEFAULT 1,
    `TR_D` INTEGER NOT NULL DEFAULT 1,
    `TDech_D` INTEGER NOT NULL DEFAULT 1,
    `Cadence` DOUBLE NOT NULL,

    PRIMARY KEY (`Id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Historique_phase4` (
    `Id` INTEGER NOT NULL AUTO_INCREMENT,
    `Date` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `Poste` ENUM('MATIN', 'APRES_MIDI', 'NUIT') NOT NULL,
    `Of` VARCHAR(191) NULL,
    `QP` INTEGER NOT NULL DEFAULT 0,
    `TQ` DOUBLE NOT NULL DEFAULT 0,
    `TP` DOUBLE NOT NULL DEFAULT 0,
    `TD` DOUBLE NOT NULL DEFAULT 0,
    `TR` DOUBLE NOT NULL DEFAULT 0,
    `TDech` DOUBLE NOT NULL DEFAULT 0,
    `TQ_AVG` DOUBLE NOT NULL DEFAULT 0,
    `TP_AVG` DOUBLE NOT NULL DEFAULT 0,
    `TD_AVG` DOUBLE NOT NULL DEFAULT 0,
    `TR_AVG` DOUBLE NOT NULL DEFAULT 0,
    `TDech_AVG` DOUBLE NOT NULL DEFAULT 0,
    `TQ_D` INTEGER NOT NULL DEFAULT 1,
    `TP_D` INTEGER NOT NULL DEFAULT 1,
    `TD_D` INTEGER NOT NULL DEFAULT 1,
    `TR_D` INTEGER NOT NULL DEFAULT 1,
    `TDech_D` INTEGER NOT NULL DEFAULT 1,
    `Cadence` DOUBLE NOT NULL,

    PRIMARY KEY (`Id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Arret_phase1` (
    `Id` INTEGER NOT NULL AUTO_INCREMENT,
    `Date_Debut` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `Date_Fin` DATETIME(3) NULL,
    `Poste` ENUM('MATIN', 'APRES_MIDI', 'NUIT') NOT NULL,
    `Of` VARCHAR(191) NULL,
    `Cause` VARCHAR(191) NULL,
    `Operateur` VARCHAR(191) NULL,

    PRIMARY KEY (`Id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Arret_phase2` (
    `Id` INTEGER NOT NULL AUTO_INCREMENT,
    `Date_Debut` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `Date_Fin` DATETIME(3) NULL,
    `Poste` ENUM('MATIN', 'APRES_MIDI', 'NUIT') NOT NULL,
    `Of` VARCHAR(191) NULL,
    `Cause` VARCHAR(191) NULL,
    `Operateur` VARCHAR(191) NULL,

    PRIMARY KEY (`Id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Arret_phase3` (
    `Id` INTEGER NOT NULL AUTO_INCREMENT,
    `Date_Debut` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `Date_Fin` DATETIME(3) NULL,
    `Poste` ENUM('MATIN', 'APRES_MIDI', 'NUIT') NOT NULL,
    `Of` VARCHAR(191) NULL,
    `Cause` VARCHAR(191) NULL,
    `Operateur` VARCHAR(191) NULL,

    PRIMARY KEY (`Id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Arret_phase4` (
    `Id` INTEGER NOT NULL AUTO_INCREMENT,
    `Date_Debut` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `Date_Fin` DATETIME(3) NULL,
    `Poste` ENUM('MATIN', 'APRES_MIDI', 'NUIT') NOT NULL,
    `Of` VARCHAR(191) NULL,
    `Cause` VARCHAR(191) NULL,
    `Operateur` VARCHAR(191) NULL,

    PRIMARY KEY (`Id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `OrdreFabrication` (
    `Id` INTEGER NOT NULL AUTO_INCREMENT,
    `Numero` VARCHAR(191) NOT NULL,
    `Article` VARCHAR(191) NOT NULL,
    `Quantite_Objectif` INTEGER NOT NULL DEFAULT 0,
    `Of_Prod` BOOLEAN NOT NULL DEFAULT false,
    `Cadence` INTEGER NOT NULL DEFAULT 0,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`Id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `NonConforme_phase1` (
    `Id` INTEGER NOT NULL AUTO_INCREMENT,
    `Date` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `Poste` ENUM('MATIN', 'APRES_MIDI', 'NUIT') NOT NULL,
    `Of` VARCHAR(191) NULL,
    `Operateur` VARCHAR(191) NULL,
    `Quantite` INTEGER NOT NULL DEFAULT 0,
    `Type` VARCHAR(191) NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`Id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `NonConforme_phase2` (
    `Id` INTEGER NOT NULL AUTO_INCREMENT,
    `Date` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `Poste` ENUM('MATIN', 'APRES_MIDI', 'NUIT') NOT NULL,
    `Of` VARCHAR(191) NULL,
    `Operateur` VARCHAR(191) NULL,
    `Quantite` INTEGER NOT NULL DEFAULT 0,
    `Type` VARCHAR(191) NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`Id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `NonConforme_phase3` (
    `Id` INTEGER NOT NULL AUTO_INCREMENT,
    `Date` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `Poste` ENUM('MATIN', 'APRES_MIDI', 'NUIT') NOT NULL,
    `Of` VARCHAR(191) NULL,
    `Operateur` VARCHAR(191) NULL,
    `Quantite` INTEGER NOT NULL DEFAULT 0,
    `Type` VARCHAR(191) NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`Id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `NonConforme_phase4` (
    `Id` INTEGER NOT NULL AUTO_INCREMENT,
    `Date` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `Poste` ENUM('MATIN', 'APRES_MIDI', 'NUIT') NOT NULL,
    `Of` VARCHAR(191) NULL,
    `Operateur` VARCHAR(191) NULL,
    `Quantite` INTEGER NOT NULL DEFAULT 0,
    `Type` VARCHAR(191) NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`Id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Dechet_phase1` (
    `Id` INTEGER NOT NULL AUTO_INCREMENT,
    `Date` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `Poste` ENUM('MATIN', 'APRES_MIDI', 'NUIT') NOT NULL,
    `Of` VARCHAR(191) NULL,
    `Operateur` VARCHAR(191) NULL,
    `Quantite` INTEGER NOT NULL DEFAULT 0,
    `Type` VARCHAR(191) NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`Id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Dechet_phase2` (
    `Id` INTEGER NOT NULL AUTO_INCREMENT,
    `Date` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `Poste` ENUM('MATIN', 'APRES_MIDI', 'NUIT') NOT NULL,
    `Of` VARCHAR(191) NULL,
    `Operateur` VARCHAR(191) NULL,
    `Quantite` INTEGER NOT NULL DEFAULT 0,
    `Type` VARCHAR(191) NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`Id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Dechet_phase3` (
    `Id` INTEGER NOT NULL AUTO_INCREMENT,
    `Date` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `Poste` ENUM('MATIN', 'APRES_MIDI', 'NUIT') NOT NULL,
    `Of` VARCHAR(191) NULL,
    `Operateur` VARCHAR(191) NULL,
    `Quantite` INTEGER NOT NULL DEFAULT 0,
    `Type` VARCHAR(191) NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`Id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Dechet_phase4` (
    `Id` INTEGER NOT NULL AUTO_INCREMENT,
    `Date` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `Poste` ENUM('MATIN', 'APRES_MIDI', 'NUIT') NOT NULL,
    `Of` VARCHAR(191) NULL,
    `Operateur` VARCHAR(191) NULL,
    `Quantite` INTEGER NOT NULL DEFAULT 0,
    `Type` VARCHAR(191) NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`Id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
