stages:
    - test
    - lint
    - build

testing:
    stage: test
    image: node:lts
    before_script:
        - npm ci
    script:
        - npm run test
    rules:
        - if: '$CI_COMMIT_BRANCH == "master" || $CI_PIPELINE_SOURCE == "merge_request_event"'
          allow_failure: false
        - if: '$CI_COMMIT_BRANCH != "master"'
          allow_failure: true

linting:
    stage: lint
    image: node:lts
    before_script:
        - npm ci
    script:
        - npm run lint
    rules:
        - if: '$CI_COMMIT_BRANCH == "master" || $CI_PIPELINE_SOURCE == "merge_request_event"'
          allow_failure: false
        - if: '$CI_COMMIT_BRANCH != "master"'
          allow_failure: true

building:
    image: docker:27-dind
    stage: build
    services:
        - docker:27-dind
    variables:
        DOCKER_TLS_CERTDIR: ''
        DOCKER_HOST: 'tcp://docker:2375'
        IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    script:
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker build -t $IMAGE_TAG .
        - docker push $IMAGE_TAG
    rules:
        - if: '$CI_COMMIT_BRANCH == "master"'
