version: '3.3'
services:
    db:
        image: mysql:latest
        restart: always
        environment:
            MYSQL_DATABASE: 'tbs'
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: 'password'
            MYSQL_ROOT_PASSWORD: 'password'
        ports:
            - '127.0.0.1:3307:3306'
        volumes:
            - ./tbs_data:/var/lib/mysql
        healthcheck:
            test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
            timeout: 20s
            retries: 10

    srv:
        image: registry.gitlab.com/aracompany/fabcom/tbs:master
        restart: always
        environment:
            NODE_ENV: 'production'
            PORT: '3001'
            DATABASE_URL: 'mysql://root:password@db/tbs'
        ports:
            - '127.0.0.1:3001:3001'
        depends_on:
            db:
                condition: service_healthy
        entrypoint: ['/bin/sh', '-c', 'npx prisma migrate deploy && npm start']

volumes:
    tbs_data:
